### ISSUE TITLE
Lil Peepz not working on go_full!

### ISSUE THREAD

**Issue by MistermaynotbeS** [DavidB2007/vyond-remastered-public#1]
When i try to open Lil Peepz on the LVM, it crashes.

**Comment by Ivorplayz** [comment]
Yeah, i know about that, its the wrapper/_THEME/action.xml file, it needs to be changed

**Comment by MistermaynotbeS** [comment]
oh yea!

**Comment by DavidB2007** [comment]
Hey, to fix lil peepz, add this file to the _THEMES folder. 
If it asks you to replace a file replace it please, this should fix the issue.
https://cdn.discordapp.com/attachments/817686570987421708/919199860257873930/action.xml
